spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academydb
    hikari:
      username: deniskochkin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
server:
  port: 8080