spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academydb
    hikari:
      username: deniskochkin
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080